# Generated by Django 4.2.6 on 2023-10-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_remove_course_credits_remove_course_ltps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='coursecredits',
        ),
        migrations.RemoveField(
            model_name='course',
            name='ltps_struct',
        ),
        migrations.AddField(
            model_name='course',
            name='Credits',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fcoursemappings',
            name='component',
            field=models.CharField(choices=[('L', 'Lecture'), ('T', 'Tutorial'), ('P', 'Practical'), ('S', 'Skilling')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fcoursemappings',
            name='section',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fcoursemappings',
            name='type',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(choices=[('CSE(R)', 'CSE(Regular)'), ('CSE(H)', 'CSE(Honors)'), ('CSIT', 'CS&IT'), ('AIDS', 'AI&DS'), ('ECEs', 'ECE'), ('EEEs', 'EEE'), ('IOTs', 'IOT'), ('Mech', 'ME'), ('CIVILs', 'CIVIL')], max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='qualification',
            field=models.CharField(choices=[('MTECH', 'MTECH'), ('PH.D', 'PH.D'), ('MS', 'MS')], max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='LTPS_struct',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
