# Generated by Django 4.2.6 on 2023-10-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_remove_course_coursecredits_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Credits',
            new_name='Credit',
        ),
    ]
